#! /bin/sh
# Look for -mpilog
logfiles=""
for arg in "$@" ; do
    if [ "$arg" = "-mpilog" ] ; then
        logfiles="/ump/hpcc/home3/mcinnes/perf/mpe/liblmpi.a"
    else
        args="$args $arg"
    fi
done
#
# You can also RUN with -tracelevel 3 or setenv MP_TRACELEVEL 3
# to get VT tracing.  Then run vt with
#  vt -tfile a.out.trc
# which will generate a file in your home directory (!)
if [ -z "$logfiles" ] ; then 
    mpcc "$@" $logfiles
else
    mpcc $args $logfiles
fi
