#! /bin/sh
# Look for -mpilog
logfiles=""
for arg in "$@" ; do
    if [ "$arg" = "-mpilog" ] ; then
	logfiles="/...whereever../liblmpi.a"
	# May also need vendors -lpmpi, if not in -lmpi
    else
        args="$args $arg"
    fi
done
#
if [ -z "$logfiles" ] ; then 
    /mpp/bin/cc -Tcray-t3d "$@" $logfiles -lmpi
else
    /mpp/bin/cc -Tcray-t3d $args $logfiles -lmpi
fi
