#! /bin/sh
# Look for -mpilog
logfiles=""
for arg in "$@" ; do
    if [ "$arg" = "-mpilog" ] ; then
	logfiles="-L/usr/people/lusk/sgimpi/mpiexmpl/maint/envs/sgi -llmpi"
    else
        args="$args $arg"
    fi
done
#
# /usr/bin/cc  $args -I/usr/people/lusk/sgimpi/mpiexmpl/src3/mpe $logfiles -lmpi
/usr/bin/cc  $args $logfiles -lmpi
